<?php

AddFaqCat("Login and Registration Issues", $db);
AddFaq(1, "Why can't I log in?", "Have you registered? Seriously, you must register in order to log in. Have you been banned from the board? (A message will be displayed if you have.) If so, you should contact the webmaster or board administrator to find out why. If you have registered and are not banned and you still cannot log in then check and double-check your username and password. Usually this is the problem; if not, contact the board administrator -- they may have incorrect configuration settings for the board or, reset your password via password reset form.", $db);
AddFaq(1, "Why do I need to register at all?", "You may not have to -- it is up to the administrator of the board as to whether you need to register in order to post messages. However, registration will give you access to additional features not available to guest users such as definable avatar images, private messaging, emailing to fellow users, usergroup subscription, etc. It only takes a few minutes to register so it is recommended you do so.", $db);
AddFaq(1, "Why do I get logged off automatically?", "If you do not check the Log me in automatically box when you log in, the board will only keep you logged in for a preset time. This prevents misuse of your account by anyone else. To stay logged in, check the box during login. This is not recommended if you access the board from a shared computer, e.g. library, internet cafe, university cluster, etc.", $db);
AddFaq(1, "How do I prevent my username from appearing in the online user listings?", "In your profile you will find an option [i]Invisible Mode[/i]; if you switch this on you will be counted as a hidden user.", $db);
AddFaq(1, "I've lost my password!", "Don't panic! While your password cannot be retrieved it can be reset. To do this go to the login page and click [u]Forgot your Password?[/u]. Follow the instructions and you should be back online in no time.", $db);
//AddFaq(1, "", "", $db);

AddFaqCat("User Preferences and settings", $db);
AddFaq(2, "How do I change my settings?", "All your settings (if you are registered) are stored in the database. To alter them click the [u]Profile[/u] link (generally shown at the top of pages but this may not be the case). This will allow you to change all your settings.", $db);
AddFaq(2, "My language is not in the list!", "The most likely reasons for this are either the administrator did not install your language or someone has not translated this board into your language. Try asking the board administrator if they can install the language pack you need or if it does not exist, please feel free to create a new translation. More information can be found at the k4 website (see link at bottom of pages)", $db);
AddFaq(2, "How do I show an image below my username?", "There may be two images below a username when viewing posts. The first is an image associated with your rank; generally these take the form of stars or blocks indicating how many posts you have made or your status on the forums. Below this may be a larger image known as an avatar; this is generally unique or personal to each user. It is up to the board administrator to enable avatars and they have a choice over the way in which avatars can be made available. If you are unable to use avatars then this is the decision of the board admin and you should ask them their reasons (we're sure they'll be good!)", $db);
AddFaq(2, "How do I change my rank?", "In general you cannot directly change the wording of any rank (ranks appear below your username in threads and on your profile depending on the style used). Most boards use ranks to indicate the number of posts you have made and to identify certain users. For example, moderators and administrators may have a special rank. Please do not abuse the board by posting unnecessarily just to increase your rank -- you will probably find the moderator or administrator will simply lower your post count.", $db);
AddFaq(2, "When I click the email link for a user it asks me to log in.", "Sorry, but only registered users can send email to people via the built-in email form (if the admin has enabled this feature). This is to prevent malicious use of the email system by anonymous users.", $db);
//AddFaq(2, "", "", $db);

AddFaqCat("Posting Issues", $db);
AddFaq(3, "How do I post a thread in a forum?", "Easy -- click the relevant button on either the forum or thread screens. You may need to register before you can post a message. The facilities available to you are listed at the bottom of the forum and thread screens (the [i]You can post new threads, You can vote in polls, etc[/i]. list)", $db);
AddFaq(3, "How do I edit or delete a post?", "Unless you are the board admin or forum moderator you can only edit or delete your own posts. You can edit a post (sometimes for only a limited time after it was made) by clicking the edit button for the relevant post. If someone has already replied to the post, you will find a small piece of text output below the post when you return to the thread that lists the number of times you edited it. This will only appear if no one has replied; it also will not appear if moderators or administrators edit the post (they should leave a message saying what they altered and why). Please note that normal users cannot delete a post once someone has replied.", $db);
AddFaq(3, "How do I add a signature to my post?", "To add a signature to a post you must first create one; this is done via your profile. Once created you can check the [i]Add Signature[/i] box on the posting form to add your signature. You can also add a signature by default to all your posts by checking the appropriate radio box in your profile. You can still prevent a signature being added to individual posts by un-checking the add signature box on the posting form.", $db);
AddFaq(3, "How do I create a poll?", "Easy -- click the relevant button on either the forum or thread screens. You may need to register before you can post a poll. The facilities available to you are listed at the bottom of the forum and thread screens (the [i]You can post polls, You can vote in polls[/i], etc. list)", $db);
AddFaq(3, "How do I edit or delete a poll?", "As with posts, polls can only be edited by the original poster, a moderator, or board administrator. To edit a poll, click the first post in the thread, which always has the poll associated with it. If no one has cast a vote then users can delete the poll or edit any poll option. However, if people have already placed votes only moderators or administrators can edit or delete it; this is to prevent people rigging polls by changing options mid-way through a poll.", $db);
AddFaq(3, "Why can't I access a forum?", "Some forums may be limited to certain users or groups. To view, read, post, etc. you may need special authorization which only the forum moderator and board administrator can grant, so you should contact them.", $db);
AddFaq(3, "Why can't I vote in polls?", "Only registered users can vote in polls so as to prevent spoofing of results. If you have registered and still cannot vote then you probably do not have appropriate access rights.", $db);
//AddFaq(3, "", "", $db);

AddFaqCat("Formatting and Thread Types", $db);
AddFaq(4, "What is BBCode?", "BBCode is a special implementation of HTML. Whether you can use BBCode is determined by the administrator. You can also disable it on a per post basis from the posting form. BBCode itself is similar in style to HTML: tags are enclosed in square braces [ and ] rather than < and > and it offers greater control over what and how something is displayed. For more information on BBCode see the guide which can be accessed from the posting page.", $db);
AddFaq(4, "Can I use HTML?", "That depends on whether the administrator allows you to; they have complete control over it. If you are allowed to use it, you will probably find only certain tags work. This is a safety feature to prevent people from abusing the board by using tags which may destroy the layout or cause other problems. If HTML is enabled you can disable it on a per post basis from the posting form.", $db);
AddFaq(4, "What are Smileys?", "Smileys, or Emoticons, are small graphical images which can be used to express some feeling using a short code, e.g. :) means happy, :( means sad. The full list of emoticons can be seen via the posting form. Try not to overuse smileys, though, as they can quickly render a post unreadable and a moderator may decide to edit them out or remove the post altogether.", $db);
AddFaq(4, "Can I post Images?", "Images can indeed be shown in your posts. However, there is no facility at present for uploading images directly to this board other than the attachments manager. Therefore you must link to an image stored on a publicly accessible web server, e.g. http://www.some-unknown-place.net/my-picture.gif. You cannot link to pictures stored on your own PC (unless it is a publicly accessible server) nor to images stored behind authentication mechanisms such as Hotmail or Yahoo mailboxes, password-protected sites, etc. To display the image use either the BBCode [img] tag or appropriate HTML (if allowed).", $db);
AddFaq(4, "What are Announcements?", "Announcements often contain important information and you should read them as soon as possible. Announcements appear at the top of every page in the forum to which they are posted. Whether or not you can post an announcement depends on the permissions required, which are set by the administrator.", $db);
AddFaq(4, "What are Sticky threads?", "Sticky threads appear below any announcements in viewforum and only on the first page. They are often quite important so you should read them where possible. As with announcements the board administrator determines what permissions are required to post sticky threads in each forum.", $db);
AddFaq(4, "What are Locked threads?", "Locked threads are set this way by either the forum moderator or board administrator. You cannot reply to locked threads and any poll contained inside is automatically ended. threads may be locked for many reasons.", $db);
//AddFaq(4, "", "", $db);

AddFaqCat("User Levels and Groups", $db);
AddFaq(5, "What are Administrators?", "Administrators are people assigned the highest level of control over the entire board. These people can control all facets of board operation which include setting permissions, banning users, creating usergroups or moderators, etc. They also have full moderator capabilities in all the forums.", $db);
AddFaq(5, "What are Moderators?", "Moderators are individuals (or groups of individuals) whose job it is to look after the running of the forums from day to day. They have the power to edit or delete posts and lock, unlock, move, delete and split threads in the forum they moderate. Generally moderators are there to prevent people going [i]off-thread[/i] or posting abusive or offensive material.", $db);
AddFaq(5, "What are Usergroups?", "Usergroups are a way in which board administrators can group users. Each user can belong to several groups (this differs from most other boards) and each group can be assigned individual access rights. This makes it easy for administrators to set up several users as moderators of a forum, or to give them access to a private forum, etc.", $db);
AddFaq(5, "How do I join a Usergroup?", "To join a usergroup click the usergroup link on the page header (dependent on template design) and you can then view all usergroups. Not all groups are [i]open access[/i] -- some are closed and some may even have hidden memberships. If the board is open then you can request to join it by clicking the appropriate button. The user group moderator will need to approve your request; they may ask why you want to join the group. Please do not pester a group moderator if they turn your request down -- they will have their reasons.", $db);
AddFaq(5, "How do I become a Usergroup Moderator?", "Usergroups are initially created by the board administrator who also assigns a board moderator. If you are interested in creating a usergroup then your first point of contact should be the administrator, so try dropping them a private message.", $db);
//AddFaq(5, "", "", $db);

AddFaqCat("Private Messaging", $db);
AddFaq(6, "How do I send a Private Message?", "To send a private message, you need to be a registered user. Once you are a registered user, go into the [url=member.php?act=profile]User CP[/url] section of the forum. Once you are in the User Control Panel, click on the [url=member.php?act=send_message]Send Message[/url] link on the left navigation bar. Fill out the form, press [b]save[/b] and you're done!", $db);
AddFaq(6, "How do I save a Message in my 'Sent Items' folder?", "To save a Private Message in your [url=member.php?act=view_folder&id=2]Sent Items[/url] folder, simply check the checkbox on the bottom of the Send Message form under the Additional Options panel.", $db);
AddFaq(6, "What is a Buddy List and how do I use it?", "A Buddy List is a very useful feature for a Private Messaging system. It allows you to specify people that you often send private messages to for use in a pop-up menu while sending messages, and it also allows you to block incoming messages from people that you don't like. To use it, insert a name into the [i]User Name[/i] field underneath your buddy list, and choose whether you like that person or not. After filling out the form, click save.", $db);
AddFaq(6, "Why can't I delete some of my messages?", "Some messages may not be deleted because they belong to a [i]conversation[/i]. That means that if someone has replied to one of your messages, or the other way around, you will not be able to remove that message. You can also not remove messages sent by any of the board Administrators.", $db);
//AddFaq(6, "", "", $db);

AddFaqCat("k4 BB Code", $db);
AddFaq(7, "What is BB Code?", "BB Code, or Bulletin Board Code, is used to represent HTML on posts, threads, forums and messages. BB Code allows for safe and simple execution of non-malicious HTML and administrator defined Emoticons.", $db);
AddFaq(7, "Basic BB Code Overview", "Here is a list of the basic BB Codes: [list]\n[*][omit][b]Bold text[/b][/omit] will produce: [b]Bold Text[/b]\n[*][omit][i]Italic Text[/i][/omit] will produce: [i]Italic Text[/i]\n[*][omit][u]Underlined Text[/u][/omit] will produce [u]Underlined Text[/u]\n[*][omit][font=Tahoma]Blah Blah[/font][/omit] will produce: [font=Tahoma]Blah Blah[/font]\n[*][omit][size=3]Blah Blah[/size][/omit] will produce: [size=3]Blah Blah[/size]\n[*][omit][color=skyblue]Blah Blah[/color][/omit] will produce: [color=skyblue]Blah Blah[/color]\n[/list]", $db);
AddFaq(7, "Advanced BB Code Overview", "Try out these BB Codes:\n\n[omit][code]text here[/code]\n[quote]quoted text here[/quote]\n[php]put PHP in here[/php][list]\n[*]List item here\n[/list]\n** Also try: [list=a] and [list=1]\n[left]Left aligned text here[/left]\n[center]centered text here[/center]\n[right]right aligned text here[/right]\n/you - will put out the session user name of the user reading the article.\n[omit][/omit] - will omit all bb code parsing within these tags[/omit]", $db);
//AddFaq(7, "", "", $db);

AddFaqCat("k4 Bulletin Board Issues", $db);
AddFaq(8, "Who wrote this bulletin board?", "This software (in its unmodified form) is produced, released and is copyrighted by [email=peter.goodman@gmail.com]k4[/email]. It is made available under the [url=http://www.opensource.org/licenses/mit-license.php]MIT license[/url] and may be freely distributed; see link for more details", $db);
AddFaq(8, "Why isn't X feature available?", "This software was written by and licensed through k4. If you believe a feature needs to be added then please visit the official k4 website and see what the k4 Group has to say. Please do not post feature requests on any of our boards, as we use sourceforge to handle tasking of new features. Please read through the forums and see what, if any, our position may already be for features and then follow the procedure given there.", $db);
//AddFaq(8, "", "", $db);

?>